version: "2"
services:
  client:
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - api
  api:
    build: ./api
    ports:
      - "8000:8000"
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
